version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Install bundler
          command: gem install bundler -v 2.2.19
      - run:
          name: pwd
          command: pwd
      - run:
          name: ls
          command: ls
      # - run:
      #     name: cd
      #     command: cd ruby
      # - run:
      #     name: ls
      #     command: ls
      # - ruby/bundle-install
      # - run:
      #     name: Initialize Ruby Exercises
      #     command: pwd
      - run:
          name: Which bundler?
          working_directory: ~/ruby
          command: bundle -v
      # - ruby/bundle-install
      - run:
          name: Which bundler?
          working_directory: ruby
          command: bundle install
